name: haskell-src-exts-util
version: 0.2.5
description: Helper functions for working with haskell-src-exts trees.
synopsis:  Helper functions for working with haskell-src-exts trees
homepage:            https://github.com/pepeiborra/haskell-src-exts-util
license:             BSD3
author:              Neil Mitchell, Jose Iborra
maintainer:          pepeiborra@gmail.com
copyright:           All Rights Reserved
category:            language
extra-source-files:
- README.md
- changelog.md

tested-with:        GHC==8.6.2, GHC==8.4.1, GHC==8.2.1, GHC==8.0.2

github: pepeiborra/haskell-src-exts-util

library: 
  source-dirs: src
  exposed-modules:
    - Language.Haskell.Exts.Util
  dependencies:
    - base < 5
    - containers
    - data-default
    - haskell-src-exts >= 1.20.0
    - transformers
    - uniplate
  when:
    - condition: impl(ghc < 8.0)
      dependencies: semigroups
